//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTAPWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollaborationImage
    {
        public int CollaborationImageId { get; set; }
        public Nullable<int> CollaborationId { get; set; }
        public Nullable<int> ImageNumber { get; set; }
        public string ImagePath { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public Nullable<int> EntryBy { get; set; }
    
        public virtual Collaboration Collaboration { get; set; }
    }
}
