//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTAPWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyDescription { get; set; }
        public string CompanyPicture { get; set; }
        public Nullable<int> IndustryId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string Founded { get; set; }
        public string CompanyUrl { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string PrimaryAdminEmail { get; set; }
        public string PrimaryAdminRole { get; set; }
        public string SecondaryAdminEmail { get; set; }
        public string SecondaryAdminRole { get; set; }
        public string ThirdAdminEmail { get; set; }
        public string ThirdAdminRole { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Interest Interest { get; set; }
    }
}
