//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTAPWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentDetailId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string ProfilePicture { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string Education { get; set; }
        public Nullable<int> Year { get; set; }
        public string Language { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string School { get; set; }
    }
}
