//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTAPWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TAPDEntities : DbContext
    {
        public TAPDEntities()
            : base("name=TAPDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CollaborationImage> CollaborationImages { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<JobType> JobTypes { get; set; }
        public DbSet<Location> Locations { get; set; }
        public DbSet<Opportunity> Opportunities { get; set; }
        public DbSet<OppportunityQuestion> OppportunityQuestions { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<UserRoll> UserRolls { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<CompanyMailContact> CompanyMailContacts { get; set; }
        public DbSet<UploadRequirment> UploadRequirments { get; set; }
        public DbSet<Collaboration> Collaborations { get; set; }
        public DbSet<Interest> Interests { get; set; }
    }
}
