//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTAPWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserForgotPassword
    {
        public int ForgotPasswordId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string PasswordActivationCode { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<bool> UserClicked { get; set; }
        public Nullable<bool> WasPasswordChanged { get; set; }
        public Nullable<System.DateTime> ClickedDateTime { get; set; }
        public string NewPassword { get; set; }
        public string OldPassword { get; set; }
    }
}
